// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Project1;

{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {DFMFileType} {ACHAT.dfm}
{ITE} {DFMFileType} {AdminCompte.dfm}
{ITE} {DFMFileType} {ConsultationAchat.dfm}
{ITE} {DFMFileType} {CONSULTATIONVENTES.dfm}
{ITE} {DFMFileType} {FactureAchat.dfm}
{ITE} {DFMFileType} {FactureVente.dfm}
{ITE} {DFMFileType} {Fournisseur.dfm}
{ITE} {DFMFileType} {PASS.dfm}
{ITE} {DFMFileType} {STATISTIQUEREGLEMENT.dfm}
{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {DFMFileType} {Unit3.dfm}
{ITE} {DFMFileType} {VENTE.dfm}
{ITE} {RCFileType} {Project1_DRC.rc}

{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'ACHAT.dfm' Form12:TForm}
{$R 'AdminCompte.dfm' Form10:TForm}
{$R 'ConsultationAchat.dfm' Form7:TForm}
{$R 'CONSULTATIONVENTES.dfm' Form8:TForm}
{$R 'FactureAchat.dfm' Form5:TForm}
{$R 'FactureVente.dfm' Form6:TForm}
{$R 'Fournisseur.dfm' Form4:TForm}
{$R 'PASS.dfm' Form11:TForm}
{$R 'STATISTIQUEREGLEMENT.dfm' Form9:TForm}
{$R 'Unit1.dfm' Form1:TForm}
{$R 'Unit2.dfm' Form2:TForm}
{$R 'Unit3.dfm' Form3:TForm}
{$R 'VENTE.dfm' Form13:TForm}
{$R 'Project1_DRC.res' 'Project1_DRC.rc'}

{$E FRA}

begin
end.